# Generated by Django 3.1 on 2020-08-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
