# Generated by Django 3.1 on 2020-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_ordering_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='time',
        ),
        migrations.AddField(
            model_name='ordering',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='p_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='How Many ?', verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='ordering',
            name='p_type',
            field=models.CharField(choices=[('S', 'Simple'), ('E', 'Egg')], default='S', help_text='Simple or Egg ?', max_length=1, verbose_name='Type'),
        ),
    ]
